#!/bin/bash

function run_black {
    if ! command -v black &> /dev/null; then
        echo "Black is not installed. Please install it and try again."
        return 1
    fi

    staged_files=$(git diff --cached --name-only --diff-filter=d | grep .py$)

    if [[ $staged_files = "" ]]; then
        return 0
    fi

    black $staged_files
    git add $staged_files
}