#!/bin/bash

function run_gitleaks {
    if ! command -v gitleaks &> /dev/null; then
        echo "Gitleaks is not installed. Please install it and try again."
        return 1
    fi
    gitleaks --path=$(git rev-parse --show-toplevel)
}